// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2l6rrlMyvkMbgTmSRb0nMamhIN8SbSsI',
    appId: '1:311756344664:web:6d83dfef58bb87fe1fe92d',
    messagingSenderId: '311756344664',
    projectId: 'weather-18525',
    authDomain: 'weather-18525.firebaseapp.com',
    storageBucket: 'weather-18525.appspot.com',
    measurementId: 'G-TKX8VRS703',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD40w15-CeoY6qJOUG86l8B2iv753ZNXi8',
    appId: '1:311756344664:android:791be09d9a63bc141fe92d',
    messagingSenderId: '311756344664',
    projectId: 'weather-18525',
    storageBucket: 'weather-18525.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX5Ra-BP1uHddWH-Cfp4MaUADlM3HACbQ',
    appId: '1:311756344664:ios:37f650833a04bfa81fe92d',
    messagingSenderId: '311756344664',
    projectId: 'weather-18525',
    storageBucket: 'weather-18525.appspot.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX5Ra-BP1uHddWH-Cfp4MaUADlM3HACbQ',
    appId: '1:311756344664:ios:d4d19e8f355501c91fe92d',
    messagingSenderId: '311756344664',
    projectId: 'weather-18525',
    storageBucket: 'weather-18525.appspot.com',
    iosBundleId: 'com.example.newApp.RunnerTests',
  );
}
